apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceRouter
metadata:
  name: api-server
  namespace: default
spec:
  routes:
    # Apply a request timeout to all traffic going to api-server
    - match:
        http:
          pathPrefix: /
      destination:
        service: api-server
        serviceSubset: stable
        requestTimeout: 10s
